name: Node.js CI

on: [push]

jobs:
  front-end:

    runs-on: ubuntu-latest
    env:
      working-directory: client
      CI: true

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - run: yarn install
    - run: yarn lint
    - run: yarn test
